### PR TITLE
Add ja.json (Japanese translation)

### PR DESCRIPTION
**Pull request by maboroshin**
I don't use Android much, so translating the Android version was a whim.

Web Front End is more willing to translate.

### CODE REVIEW

**Comment by stephane-r** [comment]
Thank you @maboroshin ! The en JSON file does not contain all the translations, it will be updated tomorrow !

**Comment by maboroshin** [comment]
Thanks, I'm in no hurry!

**Comment by stephane-r** [comment]
Hey @maboroshin , the update JSON is ready : https://github.com/stephane-r/holoplay-pwa/blob/develop/src/translations/en.json

French translation is available too !

**Comment by stephane-r** [comment]
@maboroshin Do you want to import the language into the app or do you prefer that I commit to your branch?

**Comment by stephane-r** [comment]
Hey @maboroshin 

It's okay for merge your awesome japanese translation ? I'll add in settings after :)

**Comment by maboroshin** [comment]
Go ahead! Please merge.

**Pull request merged**
