### PR TITLE
Update ja.json

### PR DESCRIPTION
**Pull request by maboroshin**
Bonjour.

### CODE REVIEW

**Comment by stephane-r** [comment]
Hey @maboroshin , thank you 👍 

Do you think it's possible to remove useless commit in this PR ?

**Comment by maboroshin** [comment]
Sorry the garbage came.😅
I think it's possible if I delete the repository once and reacquire it. In that case maybe I will do another PL again.

**Comment by stephane-r** [comment]
You can try an interactive git rebase (`git rebase -i HEAD~13` in your case) and delete the unwanted commit.

**Comment by maboroshin** [comment]
OK. I'm not familiar with rebase. If I fail, I'll PL again!

**Comment by stephane-r** [comment]
> OK. I'm not familiar with rebase. If I fail, I'll PL again!

No problem, thank you 💪

**Pull request closed without merging**
